name: build and test on pr
description: PR 시 build 와 test 를 진행

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [ '**' ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs a single command using the runner's shell
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'

      - name: Install dependencies
        run: yarn install

      # Github Repository Secrets 를 통해 환경 변수 파일을 생성합니다.
      - name: Generate Environment Variables File for Production
        shell: bash
        run: |
        while read line; do
          echo "$line" >> $ENV_FILE_PATH
        done < $ENV_FILE
        env: |
          ENV_FILE_PATH: env/.env
          ENV_FILE: ${{ secrets.ENV_FILE }}

      - name: Run build
      - run: yarn build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run test
        run: yarn run test